name: Puppeteer

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    name: ${{ matrix.os }} + node ${{ matrix.node-version }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        node-version: [10.x, 12.x, 14.x]
        os: [ubuntu-18.04, ubuntu-20.04]

    steps:
    - uses: actions/checkout@v2
    - name: Install Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - name: Install Puppeteer (and Chromium)
      run: yarn add puppeteer
    - name: Take a screenshot of a webpage
      run: node screenshot.js
    - name: Rename the screenshot
      run: mv screenshot_top.png screenshot_${{ matrix.os }}_node${{ matrix.node-version }}_top.png
      run: mv screenshot_all.png screenshot_${{ matrix.os }}_node${{ matrix.node-version }}_all.png
    - name: Save the screenshot
      uses: actions/upload-artifact@v2
      with:
        name: screenshots
        path: screenshot_${{ matrix.os }}_node${{ matrix.node-version }}*
