name: Selenium + Chromium

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    name: ${{ matrix.os }} + node ${{ matrix.node-version }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        node-version: [10.x, 12.x, 14.x]
        os: [ubuntu-18.04, ubuntu-20.04]

    steps:
    - uses: actions/checkout@v2
    - name: Install Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - name: Install Chromium
      run: |
        sudo apt-get update
        sudo apt-get install -y chromium-browser
    - name: Clone SingleFile
      run: git clone https://github.com/gildas-lormeau/SingleFile.git
    - name: Install SingleFile dependencies & chromedriver
      run: |
        cd SingleFile/cli
        npm install
        npm install chromedriver
        chmod u+x single-file
    - name: Download ublock origin for chromium
      run: |
        cd SingleFile/cli
        curl -L 'https://clients2.google.com/service/update2/crx?response=redirect&prodversion=49.0&acceptformat=crx3&x=id%3Dcgbcahbpdhpcegmbfconppldiemgcoii%26installsource%3Dondemand%26uc' > ublock_origin.crx
    - name: Make an archive of a webpage
      run: |
        cd SingleFile/cli
        export PATH="$PATH:$(pwd)/node_modules/chromedriver/bin"
        xvfb-run -s "-screen 0 1920x1080x16" ./single-file 'https://www.reddit.com/' archive_${{ matrix.os }}_node${{ matrix.node-version }}_noads.html --back-end=webdriver-chromium --browser-width=1920 --browser-height=1080 --browser-extensions="ublock_origin.crx"
        sleep 2
        xvfb-run -s "-screen 0 1920x1080x16" ./single-file 'https://www.reddit.com/' archive_${{ matrix.os }}_node${{ matrix.node-version }}_ads.html --back-end=webdriver-chromium --browser-width=1920 --browser-height=1080
    - name: Save the archive
      uses: actions/upload-artifact@v2
      with:
        name: archives_chromium
        path: SingleFile/cli/archive_${{ matrix.os }}_node${{ matrix.node-version }}*
